export default [
  {
    _id: "1234_Q1",
    course: "1234",
    title: "Week 1 Checkpoint",
    description: "Covers syllabus and basic HTML/CSS from week 1.",
    points: 20,
    available_from: "2025-10-02T00:00:00Z",
    due: "2025-10-15T23:59:00Z",
    available_until: "2025-12-15T23:59:00Z",
    published: false,
    quizType: "GRADED_QUIZ",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimitMinutes: 20,
    multipleAttempts: false,
    maxAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    questions: [
      {
        _id: "Q1_1",
        title: "HTML tag for a link",
        type: "MULTIPLE_CHOICE",
        points: 5,
        options: ["<div>", "<a>", "<img>", "<link>"],
        correctOption: "<a>",
      },
      {
        _id: "Q1_2",
        title: "CSS stands for Cascading Style Sheets.",
        type: "TRUE_FALSE",
        points: 5,
        options: ["true", "false"],
        correctOption: "true",
      },
      {
        _id: "Q1_3",
        title: "Which attribute sets the destination URL in an anchor tag?",
        type: "MULTIPLE_CHOICE",
        points: 10,
        options: ["src", "href", "link", "url"],
        correctOption: "href",
      },
    ],
  },
  {
    _id: "4000_Q1",
    course: "4000",
    title: "Python Basics",
    description: "Covers variables, loops, and functions.",
    points: 25,
    available_from: "2025-10-05T00:00:00Z",
    due: "2025-10-15T23:59:00Z",
    available_until: "2025-10-20T23:59:00Z",
    published: false,
    quizType: "GRADED_QUIZ",
    assignmentGroup: "QUIZZES",
    shuffleAnswers: true,
    timeLimitMinutes: 20,
    multipleAttempts: false,
    maxAttempts: 1,
    showCorrectAnswers: "Immediately",
    accessCode: "",
    oneQuestionAtATime: true,
    webcamRequired: false,
    lockQuestionsAfterAnswering: false,
    questions: [
      {
        _id: "Q2_1",
        title: "What keyword creates a function?",
        type: "MULTIPLE_CHOICE",
        points: 10,
        options: ["func", "def", "function", "lambda"],
        correctOption: "def",
      },
      {
        _id: "Q2_2",
        title: "range(0, 3) produces 0, 1, 2",
        type: "TRUE_FALSE",
        points: 5,
        options: ["true", "false"],
        correctOption: "true",
      },
      {
        _id: "Q2_3",
        title: "Select valid ways to declare a list",
        type: "MULTIPLE_CHOICE",
        points: 10,
        options: ["list()", "[]", "{}", "()"],
        correctOption: "[]",
      },
    ],
  },
];
